sudo: false
language: c
env:
  global: 
addons:
  apt:
    packages:
    - docbook
    - docbook-dsssl
    - docbook-xsl
    - libbsd-dev
    - libedit-dev
    - libosp5
    - libostyle1c2
    - libpam0g-dev
    - libperl-dev
    - libperl5.14
    - libpython3.2
    - openjade
    - opensp
    - python3
    - python3-dev
    - python3-minimal
    - python3.2
    - python3.2-dev
    - python3.2-minimal
    - tcl8.5
    - tcl8.5-dev
    - xsltproc
script:
- ./configure
- make docs
- make -C src/bin/psql sql_help.h
- cd doc/src/sgml
- xmllint --noout --valid postgres.xml
- zip -q postgresql-ja-html.zip -r html
- cd ../../../

deploy:
  provider: releases
  api_key:
    secure: S1PPGQDQC+fRFdg9mzB/wXai1ksw2vLEBnPQ8nbiAtiskFiFl8Wn00QD+Uq0kTd6bUbEJUm//uta34ZyG4UyEmFe5tguJYMjhjPiywmIQKD1SqPv7EjU8iq7e0/fJiwRx0si+MVVukdl4eI8AgiCbzxjziYdwYUWg3yKLhT0keo=
  file: doc/src/sgml/postgresql-ja-html.zip
  skip_cleanup: true
  on:
    repo: noborus/jpug-doc
    branch: deploy-test
    tags: true